### ISSUE TITLE
Trouble processing events after grep

### ISSUE THREAD

**Issue by pkaeding** [sonots/fluent-plugin-grep#14]
I'm sure I'm missing something basic, but it seems that if I have a `match` clause with `type grep`, no further matches will run.

For instance:

```
<match haproxy.**>
  @type grep
  regexp1 http_verb ^.+$
  add_tag_prefix access
</match>

<match **>
  @type stdout
</match>
```

With the grep match clause, I see no events.  When I remove it, I do see them.  Any ideas?

**Comment by sonots** [comment]
Maybe, your data does not match with your regexp1.

**Comment by pkaeding** [comment]
Even if the data doesn't match the regex, I should still get the unmodified event in the `stdout` matcher, right?  It would just have the unmodified tag?  Or am I misunderstanding how this works?

**Comment by sonots** [comment]
No, this plugin filters into only messages matching with regexp. Others are removed.

**Comment by pkaeding** [comment]
Oh, I see. I thought that is what the [grep filter](http://docs.fluentd.org/articles/filter_grep) did.

I guess I need something else then.

Thanks for clarifying!
