### ISSUE TITLE
Streaming error，Filter is empty！

### ISSUE THREAD

**Issue by MingqingLi** [sonots/fluent-plugin-grep#18]
<source>
  @type tail
  path /var/www/xxx/yyy/*.log
  pos_file /td-agent/buffer/xxx.log.pos
  refresh_interval 5s
  read_from_head true
  tag gold_app_api.custom
  format /^\[(?<time>[^\]]*)\] (?:(?<app_name>[^\.]+)\.(?<channel>[^\.]+)\.(?<level>[^\:]+)|(?<channel>[^\.]+)\.(?<level>[^\:]+))\: \#traceId:(?<requestId>[^ ]*) host:(?<host>[^ ]+) from:(?<from>[^ ]+) (?<other>.*)/
</source>

<match gold_app_api.custom.**>
  @type grep
  regexp1 level (^app_|^INFO)
  add_tag_prefix greped.
</match>

<match greped.gold_app_api.custom.**>
    @type file
    path /tmp/gold_app_api_custom
    timezone Asia/Shanghai
    format single_value
    time_slice_format %Y%m%d
    flush_interval 5s
    append true
    # time_format %Y-%m-%d %H:%M:%S
    buffer_type memory
    buffer_chunk_limit 4m
    buffer_queue_limit 32
    flush_interval 5s
    flush_at_shutdown true
    disable_retry_limit false
    retry_wait 1s
    retry_limit 5
</match>

The message matches, written in is empty！

**Comment by sonots** [comment]
this plugin is deprecated. Use fluentd built-in filter plugin.
