### ISSUE TITLE
Using grep plugin at the source side.

### ISSUE THREAD

**Issue by papiveron** [sonots/fluent-plugin-grep#9]
Hi,

I just have one question, cause I would like to remove some useless messages from my logs.

Can I use the grep plugin at the source side? I mean her the flentd agent/client/forwarder, where logs files are tailed and forwarded to to the server/aggregator.

Or this should be use at the server side (where all logs coming from different agents are aggregated)?

My goal is to remove undesirable log message before forwarding logs to the aggregator.

What's the best way to use it?
Thanks.

Now, from the example of the plugin using, I'm not sure the second example is correct. I l mean this :

```
<match foo.bar.**>
  type grep
  regexp1 message WARN
  regexp2 foo ^awesome$
  exclude1 message favicon
  add_tag_prefix greped
</match>
```

Assuming following inputs are coming:

```
foo.bar: {"foo":"bar","message":"2013/01/13T07:02:11.124202 INFO GET /ping"}
foo.bar: {"foo":"awesome","message":"2013/01/13T07:02:13.232645 WARN POST /auth"}
foo.bar: {"foo":"bar","message":"2013/01/13T07:02:21.542145 WARN GET /favicon.ico"}
foo.bar: {"foo":"bar","message":"2013/01/13T07:02:43.632145 WARN POST /login"}
```

You say : then output becomes as belows:
```
greped.foo.bar: {"foo":"awesome","message":"2013/01/13T07:02:13.232645 WARN POST /auth"}
```
But for me it should become :

```
greped.foo.bar: {"foo":"awesome","message":"2013/01/13T07:02:13.232645 WARN POST /auth"}
greped.foo.bar: {"foo":"bar","message":"2013/01/13T07:02:43.632145 WARN POST /login"}
```
Am I wrong?

Thanks for your reply.

**Comment by papiveron** [comment]
In fact my question is because,

On the fluentd server, I have a **match** on my logs tag, outputing them  in s3 (using **type s3**). So I would like to remove some useless messages from the logs with this same tag, then I don't konw if I use another match on the same tag, which one fluentd will use, while I want to filter messages, and send them to s3 or whatver other output plugin..

Thanks

**Comment by sonots** [comment]
You can use in either side.
What you have think is, if you use grep in the source side, the CPU resource of the source side is used. If you use grep in the aggregator side, the CPU resource of the aggregator side is used.

**Comment by papiveron** [comment]
Ok Sonots. Thanks.

As the aggregator has to much to do as it is managing logs from several sources. Here is the configuration I did on the agent, to filter aws elb health checks from my varnish server logs :

```
<source>
  type tail
  format apache2
  path /var/log/varnish/varnishncsa.log
  pos_file /var/log/td-agent/tmp/access.log.pos
  tag "row.apache2.varnish.alittlemarket.com.access"
</source>

<match row.apache2.varnish.alittlemarket.com.access>
  type grep
  input_key message
  exclude "ELB-HealthChecker"
  remove_tag_prefix row
</match>
```

With this configuration, I hope the logs beeing forwarded to the aggregator with the tag **apache2.varnish.alittlemarket.com.access** (the **grep** plugin will normally remove the **row** prefix from the tag) and without lines containing **ELB-HealthChecker** user-agent.

Do you think I'm right?

Thanks.

**Comment by sonots** [comment]
Does apache2 formatter have message field? It looks "input_key agent" is correct.

By the way, the latest fluentd has filter_grep plugin bundled. You do not need to remove_tag_prefix with it. I recommend to use the filter plugin ;)

**Comment by papiveron** [comment]
Ah thanks,

So mean this for example ?:

```
<source>
  type tail
  format apache2
  path /var/log/varnish/varnishncsa.log
  pos_file /var/log/td-agent/tmp/access.log.pos
  tag "apache2.varnish.alittlemarket.com.access"
</source>

<filter apache2.varnish.alittlemarket.com.access>    
  type grep
  exclude1 message "ELB-HealthChecker"
</filter>
```

Thanks.

**Comment by sonots** [comment]
Not "message" but "agent". Check your records with filter_stdout plugin.

**Comment by papiveron** [comment]
Ah Ok, I understand. 

You're right, it's agent.

Thanks.
